### ISSUE TITLE
coinflip always doubles money

### ISSUE THREAD

**Issue by gmpby** [deafps/CS2Silly#2]
can't lose coinflips
whenever you lose a coinflip it counts it as a win anyway
![Screenshot_1](https://github.com/deafps/CS2Silly/assets/170063212/6fa2ea26-62a0-4108-8551-a4e4027e2b6d)

**Comment by deafps** [comment]
should be fixed now
![GNKbrMIXMAAK3gO](https://github.com/deafps/CS2Silly/assets/43534349/643ff436-62e5-4056-bf50-7a49dd4edb5a)

**Comment by gmpby** [comment]
you don't gain money when you lose now but you also don't lose it (idk if its intentional)
maybe I'm dumb and its just to keep it different from roulette but thought I'd bring it up just in case
![Screenshot_3](https://github.com/deafps/CS2Silly/assets/170063212/844681ea-efc5-470c-8854-bc5ddea13ef8)
